### ISSUE TITLE
Kubernetes 介紹與使用KIND簡單建置Cluster/Local Registry - Larry's Workspace

### ISSUE THREAD

**Issue by larrylai1993** [larrylai1993/larrylai1993.github.io#1]
https://easonlai0622.github.io/2023/11/24/k8s-introduce-1/? 

 Kubernetes(K8S)Kubernetes 是一個協助我們自動化部署、擴張以及管理容器應用程式(containerized applications)的系統。相較於需要手動部署每個容器化應用程式(containers)到每台機器上，  Kubernetes(K8S) K8S 架構 什麼是 K8S 使用 KinD 架設 K8S Cluster K8S Dashboard KinD Local

**Comment by easonlai0622** [comment]
test

**Comment by f88083** [comment]
**80億人口中第一位簽到🥂**

**Comment by larrylai1993** [comment]
> @f88083
> **80億人口中第一位簽到🥂**

歡迎歡迎，熱烈歡迎
